GET endpoint for single appointment by appointmentId
Lambda-School-Labs/Express_Groomer-TeamA-BE pull request #22
Opened 2020-12-19 00:54 UTC by CodyBrewer

- feat(appointmentsModel.js): get function to get single appointment by appointmentId from database
- feat(appointmentsRouter.js): get route for /appointments/:appointmentId to get single appointment back
## Description
Endpoint on appoitnments route to get one appointment back by the appointmentID

Type
- [] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.
## Organization
- [] Have you linked this pull request to a Trello card?
- [] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
## Review
- [] Is this a work in progress?
- []  Is this ready to be reviewed?
- []  Have you added two reviewers to this pull request?

2020-12-19 01:13 UTC, ClydeFrog04 requested changes
There's a console log left behind in appointmentsModel.js on line 13

2020-12-19 01:23 UTC, CodyBrewer commented
@ClydeFrog04 Thanks for catching that log. removed it an switched over a few other i found to errors in the process

2021-01-05 01:31 UTC, ClydeFrog04 approved these changes

2021-01-05 02:15 UTC, jarrod847 approved these changes
Good Changes

2021-01-05 02:15 UTC, merged