Seed missing data
Lambda-School-Labs/Express_Groomer-TeamA-BE pull request #31
Opened 2021-01-09 17:50 UTC by CodyBrewer

## Description
Seed data for locations, locations services, customer pets and appointments table
Seed groomer id and certifications for testing

Type
- [x] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.
## Organization
- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
## Review
- [ ] Is this a work in progress?
- [x]  Is this ready to be reviewed?
- [ ]  Have you added two reviewers to this pull request?

2021-01-09 17:50 UTC, CodyBrewer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fill seed data for all tables and columns](https://trello.com/c/q2Su9UqR/57-fill-seed-data-for-all-tables-and-columns)

2021-01-09 23:53 UTC, ClydeFrog04 requested changes
Thanks for getting the rest of these written! There is a typo in the appointments.js seed file "appiointments" once that's fixed we should be good!

2021-01-11 21:02 UTC, CodyBrewer commented
@ClydeFrog04 thanks for catching that typo renamed file in the latest commit.

2021-01-12 00:39 UTC, rjsmith25 approved these changes

2021-01-12 02:37 UTC, ClydeFrog04 approved these changes

2021-01-12 02:37 UTC, ClydeFrog04 approved these changes

2021-01-12 02:37 UTC, merged